server:
  port: 8080
spring:
  application:
    name: demo-springcloud-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      url: http://www.baidu.com/
    api-b:
      path: /api-b/**
      url: http://www.sina.com/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
